### ISSUE TITLE
Syntax error of app.js file

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/dns-openmix#13]
https://github.com/jsdelivr/dns-openmix/commit/da68d536aa8186f4eccf55de1ca91046abf3a60c#diff-0364f57fbff2fabbe941ed20c328ef1aR4

Is it missing a `,` at the end of that line?

**Comment by SukkaW** [comment]
If it is an issue then I can open a PR to fix this

**Comment by jimaek** [comment]
Indeed, thank you for the PR
