### ISSUE TITLE
MaxCDN not available for Asian countries on purpose?

### ISSUE THREAD

**Issue by isaackwan** [jsdelivr/dns-openmix#3]
I was comprehending the route decision engine.. but then I noted that MaxCDN was not on the override country list on a lot of countries. May I know if that is on purpose?

-Isaac

**Comment by jimaek** [comment]
Ping on this. Do you still see the problem? MaxCDN did some changes since then

**Comment by ajkj** [comment]
problem seems to be resolved. maxcdn always point tokyo edge in Korea.

**Comment by isaackwan** [comment]
I'm pleasantly surprised that MaxCDN now supports edns-client-subnet! Thanks Dmitriy and the MaxCDN team. 😬😬😬
