### ISSUE TITLE
CDN Priority for jsDelivr to do faster delivery

### ISSUE THREAD

**Issue by vigneshshanmugam** [jsdelivr/dns-openmix#6]
If it okay if we can introduce mechanism like 

```javascript
cdnPriority = {
     "IN" : ["keycdn", "cloudfare","maxcdn"]
}


From the data above, We are pretty sure for India , KeyCDN outperforms other CDN's
```
##### Pros
We can directly serve the static assets from KeyCDN rather than going through the entire loop of checking availability, sonar and round trip time. 

##### Cons
We need to update the code when the trend gets changed by analysing the data from Cedexis. 

Please do let me know your thoughts on this.

**Comment by jimaek** [comment]
There is no point in a priority system, Cedexis works with live data and automatically selects the fastest provider. So if KeyCDN is the fastest then it will be selected anyway without your idea

**Comment by vigneshshanmugam** [comment]
Does it remembers the data for a country and choose the best CDN without analysis or compute it every time?.

**Comment by jimaek** [comment]
It computes every time. Also the data is not per country but per ASN. Only if there is no data for an ASN it fallbacks to country level data

**Comment by vigneshshanmugam** [comment]
Why cant fix that CDN for a ASN once we know and reduce the computing cost. If we see that CDN is down, then we fallback to other CDN's and then fallback to country level data at the last.

**Comment by jimaek** [comment]
The computing cost is not a problem and thats the whole point of the platform, to do real time decisions and not cached or pre-set rules

**Comment by vigneshshanmugam** [comment]
Alright thanks for the answers :)
