### ISSUE TITLE
removing exvm-sg from KR.

### ISSUE THREAD

**Issue by ajkj** [jsdelivr/dns-openmix#8]
hi i feel slowdown when cloudflare Seoul edge is not normal.

it that case man who use local dns is connected to maxcdn or keycdn, which are at least not slow. but man who use google/opendns is connected to exvmsg, which is very slow in korea.

could you remove exvm-sg from korea(KR)?

**Comment by jimaek** [comment]
I wonder why this happens. Google and OpenDNS both support EDNS

**Comment by ajkj** [comment]
only developer or power user set their dns to google dns or opendns. (below 0.5% of total)

i guess cedexis does not have not enought RUM data with opendns or google dns in korea.

and is throughput measured in custom edge(exvm-sg)? i can't find it.

![image](https://cloud.githubusercontent.com/assets/7894760/7093278/ac5da6c8-dff2-11e4-935f-05aa3475aca0.png)
![image](https://cloud.githubusercontent.com/assets/7894760/7093303/e56c83bc-dff2-11e4-8bff-7e2afa805913.png)
![image](https://cloud.githubusercontent.com/assets/7894760/7093353/59453b08-dff3-11e4-859e-32b8c2fe0040.png)
![image](https://cloud.githubusercontent.com/assets/7894760/7093627/c45c6c52-dff5-11e4-8d48-f99d94ac85e3.png)
![image](https://cloud.githubusercontent.com/assets/7894760/7093548/2d4fe640-dff5-11e4-965b-2156439df3fe.png)

**Comment by jimaek** [comment]
I removed it. Give it some time, clean your cache and try again

**Comment by ajkj** [comment]
can't wait until cloudflare(SEL) not working, anyway it will be better.
